### ISSUE TITLE
Allow require macro to unwrap result type as well as optional

### ISSUE THREAD

**Issue by CamJN** [swiftlang/swift-testing#609]
### Description

It would be very nice to be able to use the `require` macro to get the success value from a result similar to how you can require than an optional return value is not nil.

### Expected behavior

Something like this would be nice:

`let inner_value = try #require(Class.resultReturningMethod())`

### Actual behavior

Have to write something like this:

`let inner_value = try #require(try Class.resultReturningMethod().get())`

### Steps to reproduce

This is a feature request so reproduction isn't really relevant, since the feature doesn't exist yet.

### swift-testing version/commit hash

0.11.0

### Swift & OS version (output of `swift --version && uname -a`)

```
<unknown>:0: warning: using (deprecated) legacy driver, Swift installation does not contain swift-driver at: '/Library/Developer/CommandLineTools/usr/bin/swift-driver-new'
Apple Swift version 6.0 (swiftlang-6.0.0.7.6 clang-1600.0.24.1)
Target: x86_64-apple-darwin24.0.0
Darwin Camdens-Mac 24.0.0 Darwin Kernel Version 24.0.0: Thu Jun 20 20:36:19 PDT 2024; root:xnu-11215.0.115.501.3~1/RELEASE_X86_64 x86_64
```

**Comment by grynspan** [comment]
Thanks for filing, @CamJN! This feature isn't necessary because you can simply write:

```swift
let inner_value = try Class.resultReturningMethod().get()
```

If the `Result` is of case `.failure()`, its error will be thrown from the test function and will be reported as a test failure.

**Comment by CamJN** [comment]
@grynspan I may be mistaken but I think your snippet has some different behaviour than I was trying to describe.

I believe that `let inner_value = try Class.resultReturningMethod().get()` will not fail if `inner_value` is not truthy, correct? That was an important part of what I was trying to do, I didn't mention it because it's just part of how `try #require` works.

**Comment by grynspan** [comment]
I'm not sure what you mean by "not truthy" here. Do you mean you're specifically interested in `Result<Bool, _>`? Such a value can also be handled already:

```swift
let inner_value = try Class.resultReturningMethod().get()
try #require(inner_value)
```

**Comment by CamJN** [comment]
I just mean that similar to how if you pass in an optional, it ensures that the value is non-nil and not false, if you pass in a result, it would be really nice if it ensured that the value was success and does not contain false.

I know it's possible to do so with extra checks, but it would be nicer if it was combined.

**Comment by grynspan** [comment]
> I just mean that similar to how if you pass in an optional, it ensures that the value is non-nil and not false, if you pass in a result, it would be really nice if it ensured that the value was success and does not contain false.

It doesn't do that, actually. If you pass a value of type `Bool?`, you'll actually get a warning about it being ambiguous. :)

**Comment by CamJN** [comment]
Oh, oops. I was under the impression that it did both. Might be worth putting a note in the docs about that.
