### ISSUE TITLE
Use OSLog for reporting test results

### ISSUE THREAD

**Issue by bnickel** [swiftlang/swift-testing#705]
### Description

I'm not sure if this applies to Xcode or Swift Testing or both, but currently test results are written directly to the console without any annotation.  If OSLog were used, it would be possible to filter by library or category in Xcode and Console.app, suppressing extraneous messages.

### swift-testing version/commit hash

Xcode 16.0 default version

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Darwin KJF2YPJGW7 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64

**Comment by grynspan** [comment]
Thanks for filing this! `os.Logger` is an Apple-specific API and it looks like your use case for adopting it is specific to Xcode. When you're using Swift Testing within Xcode, Xcode's integration with Swift Testing is responsible for handling the standard I/O streams and determines where messages are logged.

I'm closing this issue, but please don't take that as me/us rejecting your proposal. Would you mind filing [feedback](https://feedbackassistant.apple.com) with Apple regarding this suggestion, then letting us know the "FB" number here? The Xcode team will be able to triage this issue better than we can on GitHub. Thanks!
