### ISSUE TITLE
Support Crash Expectations

### ISSUE THREAD

**Issue by ed-irl** [swiftlang/swift-testing#729]
### Description

There's a long discussion of this topic [on the swift forums](https://forums.swift.org/t/testing-fatalerror-and-friends/67317/70). It would be extremely helpful if there was a way to assert crash behavior. This would still be useful even if it was platform-dependent (eg. not supported on IOS). Also related to [#156](https://github.com/swiftlang/swift-testing/issues/156).

**Comment by ed-irl** [comment]
Whoops looks like this was addressed - https://github.com/swiftlang/swift-testing/pull/307

**Comment by grynspan** [comment]
Duplicate of #307
