### ISSUE TITLE
Desire #require with Never.self so as to show source location of caught error

### ISSUE THREAD

**Issue by bernoulliconvergenator** [swiftlang/swift-testing#751]
### Description

Understandably `try #require(throws: Never.self) is redundant. Invoke non-throwing test code directly instead`. 

But "testing code directly" that results in an unwanted error then does not provide information for the `#require` that experienced the error. The test failure is only noted at `@Test` up in the function header.

Workaround found with `try #require("a comment if desired", performing: { try couldThrowButShouldNot() }, throws: { _ in false })` but not ideal.

### Expected behavior

`try #require(try couldThrowButShouldNot())` should show failure `Expectation failure: unexpected error ..` at `#require` source location.

`try #require(throws: Never.self, "this thing didn't work out because .. ", performing: { .. }` 

### Actual behavior

`try #require(try couldThrowButShouldNot())` shows context-less failure `Caught error ..` at `@Test` in function header.

### swift-testing version/commit hash

Xcode 16

### Swift & OS version (output of `swift --version && uname -a`)

```
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
Darwin MyMac.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:52:31 PDT 2024; root:xnu-11215.1.10~2/RELEASE_ARM64_T6030 arm64
```

**Comment by grynspan** [comment]
Instead of wrapping your throwing code in `#require`, simply invoke it directly:

```swift
@Test func f() throws {
  try couldThrowButShouldNot()
}
```

Swift Testing will report the test failure as intended. You're using Xcode, so the failure should be attributed to the line that threw the error as in this example:

<img width="750" alt="Screenshot 2024-10-07 at 4 25 06 PM" src="https://github.com/user-attachments/assets/c6b30161-24d4-4c31-8cf1-e3ff34bfcb13">

**Comment by bernoulliconvergenator** [comment]
@grynspan the more direct option without `#require` also reports error without context at function header.

<img width="441" alt="image" src="https://github.com/user-attachments/assets/97904c80-a7c9-4ec8-89c5-61859ee45962">

**Comment by grynspan** [comment]
Sounds like you may be running into an issue with the Xcode user interface. If you install the Xcode 16.1 beta, do you see better output similar to what I showed you? If not, please file feedback with Apple at https://feedbackassistant.apple.com. Thanks!
