### ISSUE TITLE
Unable to call a throwable async function using expect attached macro 

### ISSUE THREAD

**Issue by azamsharpschool** [swiftlang/swift-testing#755]
### Description

I have the following unit test: 

```
@Test
    func throwErrorIfAccountBalanceIsLessThan1000() {
        
        let bankAccount = BankAccount(balance: 250, accountHolder: "John Doe", accountNumber: "987654", ssn: "345-23-3212")
        
        let mockedCreditScoreService = CreditScoreServiceMock(creditScore: 700)
        let loanService = LoanService(creditScoreService: mockedCreditScoreService)
        
        #expect(throws: LoanServiceError.self, performing: {
            try await loanService.applyForLoan(bankAccount: bankAccount, amount: 5000)
        })
    }
```

The loanService.applyForLoan is an async throws function. The test does not compile and throws the following error: 

```
async' call in a function that does not support concurrency
```

The error is coming from the code inside the performing closure. The performing closure is an async closure so it should allow for await to be used. 

Is this a bug and what is the suggested workaround? 

### Expected behavior

The compiler should not complain since performing is an async closure and inside the async closure, it should be allowed to use await. 

### Actual behavior

The compiler complains and throws a compile time error. 

### Steps to reproduce

1. Use the code provided in the description above.

**Comment by grynspan** [comment]
The calling function must also be `async` and you must use `await` with `#expect`:

```swift
@Test func throwErrorIfAccountBalanceIsLessThan1000() async {
        let bankAccount = BankAccount(balance: 250, accountHolder: "John Doe", accountNumber: "987654", ssn: "345-23-3212")
        
        let mockedCreditScoreService = CreditScoreServiceMock(creditScore: 700)
        let loanService = LoanService(creditScoreService: mockedCreditScoreService)
        
        await #expect(throws: LoanServiceError.self, performing: {
            try await loanService.applyForLoan(bankAccount: bankAccount, amount: 5000)
        })
    }
```
