### ISSUE TITLE
Swift Testing with PassThroughSubjects/CurrentValueSubject

### ISSUE THREAD

**Issue by es-tinh-nguyen** [swiftlang/swift-testing#771]
I am trying to write test cases for code using the Combine framework.

I have a `CurrentValueSubject<Bool, Never>(false)` in my code.
Suppose there is a function that may or may not use this subject to send event `subject.send(true)`,
I want to test that this subject `sends at least 1 event (1)`, and `doesn't send any event (2)`

For case (1), I use this code and it works well
```
let subjectValues = await subject.values.first(where: { $0 })
let isTrigger = try #require(values as Bool?)
#expect(isTrigger == true)
```

For case (2), we can achieve it using `XCTestExpectation.isInverted` like the code below
```
let expectation = XCTestExpectation(description: "No event should be sent")
expectation.isInverted = true // Invert the expectation to test that no event is received

subject
    .dropFirst() // Ignore the initial value
    .sink { _ in
        expectation.fulfill()
    }
    .store(in: &cancellables)
wait(for: [expectation], timeout: 1.0)
```
My question is **How can we test case (2) using Swift Testing**? Thank you!

**Comment by grynspan** [comment]
I'm closing this issue as we've given you an answer to your question, but if we've missed anything please do let us know here or on the Swift Forums. Thanks!
