### ISSUE TITLE
[Question] addTeardownBlock equivalent in Swift testing

### ISSUE THREAD

**Issue by PabloButron** [swiftlang/swift-testing#774]
I am migrating tests from XCTest to Swift Testing and I want to migrate a test with a function who has inside:

addTeardownBlock (to prevent memory leaks) I couldn’t find an equivalent in swift testing only find init and deinit.

Is something equivalent or any trick to do this?

Here is the function:

`private func trackForMemoryLeaks ( _ instance: AnyObject ) {
addTeardownBlock { [ weak instance ] in
XCTAssertNil(instance)
}
}`

thanks in advance

**Comment by grynspan** [comment]
In your suite, you can add a stored property and a deinitializer:

```swift
weak var weakObject: AnyObject?

deinit {
  #expect(weakObject == nil)
}
```

And in your test, to set the object you want to look at in `deinit`:

```swift
@Test func f() {
  ...
  weakObject = ...
  ...
}
```

If you need to track more than one weak reference, there are a few options for creating a collection of them that you can find online. 🙂

**Comment by grynspan** [comment]
Oh, or even simpler:

```swift
@Test func f() {
  weak var weakObject: AnyObject?
  defer {
    #expect(weakObject == nil)
  }
  ...
  weakObject = ...
}
```

**Comment by sems** [comment]
@PabloButron Did you find a final maintainable solution?

**Comment by PabloButron** [comment]
Just didn't migrate tests yet, another stuff with higher priority appear... but if you find anything new, I'm curious too...
