### ISSUE TITLE
Add `confirmation` to the XCTest vs SwiftTesting lookup table in docs

### ISSUE THREAD

**Issue by MahdiBM** [swiftlang/swift-testing#775]
### Description

https://swiftpackageindex.com/swiftlang/swift-testing/main/documentation/testing/migratingfromxctest#Record-issues
Does not mention `confirmation` is a (partial?) counterpart to `XCTestExpectation`.
Would be nice to have it there in the lookup table.

**Comment by grynspan** [comment]
It's documented lower down. https://swiftpackageindex.com/swiftlang/swift-testing/main/documentation/testing/migratingfromxctest#Validate-asynchronous-behaviors

**Comment by MahdiBM** [comment]
@grynspan I did notice that, but it's still not in the lookup table. Would be nice to have a place for quick lookups.

One of the reasons i was thinking maybe SwiftTesting doesn't have an equivalent to `XCTestExpectation` was the fact that i didn't see it mentioned in that table and i thought if it existed it must have been there.

**Comment by MahdiBM** [comment]
I did notice that as well 🙈 just saying it would be nice if there was a quick lookup table with all the functions and their equivalents in them.

It's not like it'll affect me personally, I already learnt these the hard way, but I imagine I wasn't the first and won't be the last person that tried to cheat in reading the article by just taking a look at that table, a few months ago 😅
