### ISSUE TITLE
enable opting-out of thrown Error tracing

### ISSUE THREAD

**Issue by tayloraswift** [swiftlang/swift-testing#791]
### Description

follow up from Slack: https://swift-open-source.slack.com/archives/C06QXFKB4ER/p1730243185369769

running tests with Testing, even in `-c release` mode, results in an >100x slowdown when using certain libraries such as [swift-json](https://github.com/tayloraswift/swift-json) due to the way it parses UTF-8 text internally. this in turn is because [swift-grammar](https://github.com/tayloraswift/swift-grammar), which swift-json’s parser is implemented in, throws an Error on nearly every input character. 

### Expected behavior

there should be a way to locally disable Error tracing so we can use these libraries within test runners.

### Actual behavior

it takes many minutes to parse a large JSON file within a test runner, which should only take a couple seconds.

### Steps to reproduce

https://github.com/tayloraswift/swift-json/pull/80 demonstrates the problem

### swift-testing version/commit hash

6.0.1

**Comment by grynspan** [comment]
@tayloraswift and I discussed this in Slack briefly. It'd be great if you can get some backtraces from during the hang so we can confirm the theory before we make a speculative change.
