### ISSUE TITLE
Missing docs on how to consume from SPM (on Windows)

### ISSUE THREAD

**Issue by tristanlabelle** [swiftlang/swift-testing#860]
### Description

I'm not finding any docs on how to reference this project from SPM. I tried a straightforward

```swift
    dependencies: [
        .package(url: "https://github.com/apple/swift-testing.git", from: "6.0.3")
    ],
```

As well as `exact: "6.0.3"`. In both cases, the build then fails with `"Testing" contains unsafe build flags`. I was able to get it to work with an explicit commit hash but that's not great:

```swift
    dependencies: [
        .package(url: "https://github.com/apple/swift-testing.git", revision: "18c42c19cac3fafd61cab1156d4088664b7424ae"), // 6.0.3
    ],
```

Am I doing it wrong? Docs would help.

### swift-testing version/commit hash

6.0.3

### Swift & OS version (output of `swift --version && uname -a`)

compnerd.org Swift version 6.1-dev (LLVM 80d178d8cbb1cee, Swift fb259eaa4980e29)
Target: x86_64-unknown-windows-msvc

**Comment by grynspan** [comment]
Swift Testing is part of the Swift 6 toolchain. There are no instructions on adding a package dependency because you don't need one. You can simply `import Testing` in your test target.
